### ISSUE TITLE
small text change

### ISSUE THREAD

**Issue by lauraguzman** [the-engine-room/2019-retro#7]
Hey @IronRunes - I would do this but my version isn't up to date and I can't figure out how to just override the version I have and start afresh, so. Here we are.

Could you change each instance of "direct support" in the text to "regional support"? That would mean in the following spots:
- [x] the orange box after Julia's letter
- [x] the button selector for the different story categories
- [x] the story named "DEEPENING OUR DIRECT SUPPORT"
- [x] the little icon + name that appears in each story under "direct" (now "regional" support)

Alternatively, if TRAVIS will take my changes if I do them within github's web interface, I can give it a whirl tomorrow!

**Comment by IronRunes** [comment]
Got this done! 
Btw, Travis will indeed deploy changes as long as you commit them to the right branch (gh-pages)
